FRED_API_KEY = "d71784c269c4248475203d3e28d1bb73"
GDRIVE_FOLDER_ID = "1iaEx3DulLCfPVCbfJkhOY4eeRj-b3PGH"
GDRIVE_CREDENTIALS_JSON = "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAi
bWFjcm8tc3JhdGVneS1hcHAiLAogICJwcml2YXRlX2tleV9pZCI6ICJhYTE1ZmQz
MmVmOTRmY2ZkZTRkZTE0MjBjMzEzMDYxMTlkNDQ0NDlhIiwKICAicHJpdmF0ZV9r
ZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdmdJQkFEQU5C
Z2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUURUbm8xaXJFU2xF
MUhkXG5DODNXUmFlekU2OHRRemN3T29mZE5MYUVzUDU0N05qbWVtLzdHZ0dxaDA2
SHBCZHlCcjhyMmpyUnR1ZUFTa2h4XG5yRUprQWlaWGdHdGIrVEkrUDlpeFkrTjg5
a0xDcTliaXo5Q0VUOVRSMmgrdlVZa2pFeXdvSUVkVE5CSW1yd05yXG5LSVh1OVcv
UU5vWUx6QkpTS3o1KzFtUFNsUnNzeGcrdjdGdGJGdWJ5UERSZnlPaW9ydm8xMGYr
ZnNRYUlxWTBOXG5nTi9WY3JPL1V2bXkvYWdleitoUEZzZktUc3p5cmN6K0VsM1k1
NmFiYVh0SUdrZHVoNENEL1JxZ0xTU2c2OXZsXG5jWEFyU1BDRlNlaTk1dmtsOUdP
bmZHOGZodmQwSDd6a2E1YmRQQ3NZOTlpVFFTaURCRWZXMDRnQlBSUVRkd3FPXG5K
MVZRVVJYUEFnTUJBQUVDZ2dFQUdocHdyajg1cUhNZG9mcVd4VnVLT0JpeGZ3L1Bl
dTk5V3RmcHU2eHBkMWtmXG4yQzQ2S2VzblVYV25SaXdEaUZrMHM2QVRxVks2YzZT
MkV1K0FzUDFpNVdBOTNmWjdNQnFJRERtYUVndithQ3p5XG5NTUFacEhpRWMrNUlB
a1E0ZWs4ZkgwUDhDRk5mK2MyVXlsOFJSa3lZSWtMWGZoVUtIWUNnRU4wNUt2eWhn
WUFqXG5VdVI4Tk5ZNHhCMk9tbEovWjI2cU5aVlc4NUdzK0FnZlkwYzl2dkFEUmlk
RHhFOU55bnhJdEdUNW1sa01qMkFpXG55L2wrYjFBbXBPeTlnMjRJcTRrbmUyODhW
dVRVU0xBYXhoeUk5TkJDSjUrV3ZJZGtNSktxSHNLUytKQ0pDT2Q4XG5ibjh4ZkRw
aGZaM0hUL2hKOGt2b3VMSEJlZVJjSjYxcEtobWRsYTFFNFFLQmdRRDZyTFNNWnVz
WnM5VjhUNVVIXG5HNmJxaWtaZXhtdFR5a25zdWM3bjhITUFKVnZQOEhkVzcxREVB
VXd2cnR5TFBoa3AybWszcEdsd2Q5TVN6RjNZXG5PUXQxREw0RFM3WE9LaFkrWXhF
V1hNdXNleEZueGJHRmhtWncrMktxTElCbTdvNFpyZ1dObW5jaWRHOWE0WXczXG53
WVVkN2d2NmRUcU5jWlZ2VloxM2NyYk5Xd0tCZ1FEWUhYSGFEeE10VCs5UFQ2RWtm
NG40L1FJc3FlQzVxQXVKXG5LbEZKWnFjM1JRUW1PZ0QrYWRObktnUnJTWmpNaGJE
UTNSaXJUMFBobmJlRXViRW9XY2Z6Z2F5S2lEeTNNU2RWXG5uZ01tdDBVdkJEWkdr
aXdPS1doZVMrK28rNGMxNkRweVFVM1h3RTNJYTg3ajNJaXNCTk9PbDhKS2JFakRU
bHN1XG56bzN1R2c5L25RS0JnUUNOTlhqSGxycGRVamF5dmtuZkpTNlQ5S3pMZXM2
KzlyZEtDU21LOHFKMXRKWFJ2MDRhXG54TmtrY082djlicjdIVklqaDR1NThuNExB
eFQrQSszaGZkRDhjTjhoRUNjc0tmMDV5NmkyaGpPZHgvMzREUitCXG5ia0tLNXJH
ZjEwM0ZyaUNTU3J1S0Z6ZUJTMEhuV2lNWXpZVGxaVkdPRnplU3NpZFIvbEtrRlJU
dy9RS0JnQ2N2XG5kNVJOUlhIaTI0WnE3dEg2V2g4T2FSV0dHOXd0N3lHSXpjSmNY
WmQwNlNLeFE3cmRuMXBHVVJUTy9HaWhHUVZXXG5BWUlXVmoyVFpsSW5oVXJHdEsy
ZlpwU2J6VDUrS0I2ckR2RTNLOUV4bDFIR2NUeUVINHR4ZzF3RmQyZTcydFVhXG5x
QzJsamJUNGIwUDdtY0J2QTVrSVJVOVBRUVpBcitIVnpBQlBNMTQxQW9HQkFPUVFa
MHFaMEkvMDM0QXgxUTJqXG5BWUJNQnlDeFE2dUVjbzd2UzM4QmZHTHFZMDRIcGV0
TzhLQXFNbXZFdXRad1ltUi9hVXpZR3QydGUvcXJqdURmXG41TWVqNmpLZDZ6bkU4
NTBnQ2l6SjlqdUtLVnJmTy9aaUtuVWdScFNiZ2RlZmlFNGRRdENzdnlmRCtJaTVR
MEozXG50SmI1cm13QnVpS3pJL2J2QVgxUXhRcnhcbi0tLS0tRU5EIFBSSVZBVEUg
S0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJtYWNyby1zdHJhdGVneS1h
cHBAbWFjcm8tc3JhdGVneS1hcHAuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAog
ICJjbGllbnRfaWQiOiAiMTAxNzQ2MDA3MTQ0MDIzNzE1MzA1IiwKICAiYXV0aF91
cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgi
LAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20v
dG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6
Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50
X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9i
b3QvdjEvbWV0YWRhdGEveDUwOS9tYWNyby1zdHJhdGVneS1hcHAlNDBtYWNyby1z
cmF0ZWd5LWFwcC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgInVuaXZlcnNl
X2RvbWFpbiI6ICJnb29nbGVhcGlzLmNvbSIKfQo="